FROM --platform=linux/arm64 public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

RUN yum install -y gcc gcc-c++ make libxml2-devel libxslt-devel && yum clean all

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD ["handler.handler"]